version: '2'

services:

  database:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    command: mysqld --user=root --verbose
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test_db"
      MYSQL_ROOT_PASSWORD: "root"